### ISSUE TITLE
X-App-Token有办法计算么? LOL

### ISSUE THREAD

**Issue by ruixingchen** [unnamed5719/coolapk-users#2]
想做一个酷安的iOS客户端, 老接口快要无法正常工作了, 哎, 😔

**Comment by unnamed5719** [comment]
你可以用V5的api，算法写在了java里面，现在还是可以用的(至少是看看评论什么的)

**Comment by ruixingchen** [comment]
@unnamed5719  不能用了啊, 获取评论列表已经只能返回空数组了

**Comment by unnamed5719** [comment]
进入到个人页面还是可以看到动态的：P

**Comment by ruixingchen** [comment]
@unnamed5719  然而评论是核心啊, 刚看了下.so的汇编, 吐了, -_-, 准备想其他方法
