### ISSUE TITLE
酷安已死，有事烧纸

### ISSUE THREAD

**Issue by iVanilla** [unnamed5719/coolapk-users#3]
本人宣布对之前发动的针对酷安的 DDoS 攻击负责 (

**Comment by unnamed5719** [comment]
！？？？？

**Comment by iVanilla** [comment]
@unnamed5719 作为酷安曾经的活跃分子之一，看到酷安现在这种样子确实很不爽，酷安乙烷是大家都知道的。

这也是我成立 @Geekapk 的原因之一。

**Comment by unnamed5719** [comment]
@iVanilla 网站无法打开 

> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by iVanilla** [comment]
@unnamed5719 急啥，网站还在开发中，你可以加入我们的 telegram 群组，username 也是这个

**Comment by unnamed5719** [comment]
@iVanilla 飞机场提供商跑路，要等一段时间了...sad

**Comment by iVanilla** [comment]
@unnamed5719 换一家能用的不就行了

**Comment by unnamed5719** [comment]
@iVanilla 暂时找不到（（

**Comment by iVanilla** [comment]
@unnamed5719 那是你的问题，我们这些人天天在各种 telegram 群里谈笑风生，他们怎么找到梯子的？
